import pprint
import pymongo


try:
	client = pymongo.MongoClient()
	db = client['test']
	print('connection to the server established')

except Exception:
	print('Failed to Connect to server')

collection = db.students

# dropping the index using autogenerated
# name from MongoDB
collection.drop_index("newIndex_1")

# printing the indexes present on the collection
pprint.pprint(collection.index_information())
