import pprint
import pymongo

try:
    client = pymongo.MongoClient()
    db = client['GFG']
    print('connection to the server established')

except Exception:
    print('Failed to Connect to server')

collection = db.lecture

# dropping the index using autogenerated
# name from MongoDB
collection.drop_indexes()

# printing the indexes present on the collection
pprint.pprint(collection.index_information())
